- word: Mannschaft
  translations:
    - team
    - squad
  extra: die Mannschaft, -en
  definition: Gruppe von Sportlern, die zusammen spielen.
  examples:
    - Unsere Mannschaft hat das Spiel gewonnen.
    - Die Mannschaft hat ein Training.
  image_query_words: [team]

- word: warten + auf + akk.
  translations:
    - to wait
    - await
  extra: haben + gewartet
  definition: Auf etwas oder jemanden in einer bestimmten Zeit warten.
  examples:
    - Ich habe auf den Bus gewartet.
    - Wir haben lange auf dich gewartet.
  image_query_words: [waiting]

- word: sich + erinnern + an + akk.
  translations:
    - to remember
  extra: haben + sich + erinnert
  definition: jemanden an etwas erinnern
  examples:
    - Er erinnert mich an den Termin.
    - Kannst du dich daran erinnern?
  image_query_words: [memory]
