name: PyPI Release

on:
  push:
    branches:
      - main

jobs:
  pypi_release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      PACKAGE_VERSION: ${{ steps.get_current_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Python version
        id: python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Get current version
        id: get_current_version
        run: echo "::set-output name=version::$(poetry version -s)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_current_version.outputs.version }}
          release_name: Release v${{ steps.get_current_version.outputs.version }}
          body: Release of version v${{ steps.get_current_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Configure PyPI
        if: steps.create_release.outputs.id != '' # Release was created successfully
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Build package
        if: steps.create_release.outputs.id != ''
        run: poetry build

      - name: Publish package to PyPI
        if: steps.create_release.outputs.id != ''
        run: poetry publish

  build-and-push:
    needs: pypi_release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read Python version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/germanki:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/germanki:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/germanki:${{ needs.pypi_release.outputs.PACKAGE_VERSION }}
          # Build arguments, if needed
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
